-- Run once in Supabase Dashboard -> SQL Editor

create type userrole as enum ('foreman', 'worker');
create type taskstatus as enum ('open', 'in_progress', 'review', 'done');

create table users (
  id integer generated by default as identity primary key,
  telegram_id bigint not null unique,
  phone varchar(20) not null unique,
  name varchar(100) not null,
  role userrole not null,
  lang varchar(5) not null default 'ru',
  notifications boolean not null default true,
  created_at timestamp not null default (now() at time zone 'utc')
);
create index ix_users_telegram_id on users (telegram_id);

create table sites (
  id integer generated by default as identity primary key,
  name varchar(200) not null,
  address varchar(300) not null,
  foreman_id integer not null references users(id) on delete cascade,
  invite_code varchar(32) not null unique,
  photos_json text not null default '[]',
  videos_json text not null default '[]',
  created_at timestamp not null default (now() at time zone 'utc')
);
create index ix_sites_invite_code on sites (invite_code);
create index ix_sites_foreman_id on sites (foreman_id);

create table site_members (
  id integer generated by default as identity primary key,
  site_id integer not null references sites(id) on delete cascade,
  worker_id integer not null references users(id) on delete cascade,
  unique (site_id, worker_id)
);

create table tasks (
  id integer generated by default as identity primary key,
  site_id integer not null references sites(id) on delete cascade,
  title varchar(200) not null,
  description text not null default '',
  status taskstatus not null default 'open',
  created_by integer not null references users(id),
  taken_by_id integer references users(id),
  photo_id varchar(255),
  created_at timestamp not null default (now() at time zone 'utc')
);
create index ix_tasks_site_id on tasks (site_id);

create table task_reports (
  id integer generated by default as identity primary key,
  task_id integer not null references tasks(id) on delete cascade,
  worker_id integer not null references users(id),
  comment text not null default '',
  photos_json text not null default '[]',
  created_at timestamp not null default (now() at time zone 'utc')
);

create table task_reviews (
  id integer generated by default as identity primary key,
  task_id integer not null references tasks(id) on delete cascade,
  foreman_id integer not null references users(id),
  comment text not null default '',
  created_at timestamp not null default (now() at time zone 'utc')
);

create table messages (
  id integer generated by default as identity primary key,
  site_id integer not null references sites(id) on delete cascade,
  user_id integer not null references users(id),
  text text not null default '',
  photo_id varchar(200),
  sent_at timestamp not null default (now() at time zone 'utc')
);
create index ix_messages_site_sent on messages (site_id, sent_at desc);

-- Security: block public REST access (anon/authenticated keys).
-- The bot connects as the postgres role, which bypasses RLS.
alter table users enable row level security;
alter table sites enable row level security;
alter table site_members enable row level security;
alter table tasks enable row level security;
alter table task_reports enable row level security;
alter table task_reviews enable row level security;
alter table messages enable row level security;
